name       : perl-namespace-autoclean
version    : '0.29'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/namespace-autoclean-0.29.tar.gz : 45ebd8e64a54a86f88d8e01ae55212967c8aa8fed57e814085def7608ac65804
homepage   : https://metacpan.org/pod/namespace::autoclean
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : namespace::autoclean - Keep imports out of your namespace
description: |
    When you import a function into a Perl package, it will naturally also be available as a method. The namespace::autoclean pragma will remove all imported symbols at the end of the current package's compile cycle. Functions called in the package itself will still be bound by their name, but they won't show up as methods on your class or instances.
builddeps  :
    - perl-b-hooks-endofscope
    - perl-namespace-clean
    - perl-sub-identify
    - perl-test-needs
    - perl-test-requires
rundeps    :
    - perl-b-hooks-endofscope
    - perl-namespace-clean
    - perl-sub-identify
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
