name       : perl-namespace-autoclean
version    : 0.28
release    : 6
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/namespace-autoclean-0.28.tar.gz : cd410a1681add521a28805da2e138d44f0d542407b50999252a147e553c26c39
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Keep imports out of your namespace
description: |
    Keep imports out of your namespace
builddeps  :
    - perl-b-hooks-endofscope
    - perl-namespace-clean
    - perl-sub-identify
    - perl-test-requires
rundeps    :
    - perl-b-hooks-endofscope
    - perl-namespace-clean
    - perl-sub-identify
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
